version: '3.9'

services:
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/app
    environment:
      POSTGRES_URI: postgresql://postgres:9699511Hk!@db.zibaknnfiuehdirbciuh.supabase.co:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
