services:
  smart-brain-api:
    container_name: backend
    build: .
    working_dir: /usr/src/app
    command: npm start
    environment:
      POSTGRES_URI: postgresql://postgres.zibaknnfiuehdirbciuh:9699511Hk!!@aws-1-us-east-1.pooler.supabase.com:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
