services:
  smart-brain-api:
    container_name: backend
    build: .
    working_dir: /usr/src/app
    command: npm start
    environment:
      POSTGRES_URI: postgresql://postgres:9699511Hk!!@db.zibaknnfiuehdirbciuh.supabase.co:5432/smartbrain-db
      REDIS_URL: https://modest-oryx-26067.upstash.io
      REDIS_TOKEN: AWXTAAIncDE0YjYzMjE1MmU1OGY0ZWE5ODkzOTk3MGMwNGEzOGMyY3AxMjYwNjc
      JWT_SECRET: uR9&hG2#xL!p7@dT5zF8qQwR1vN0sM6j
      PORT: 3000
    ports:
      - "3000:3000"
